# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6490f82a1361a9091b8d31f545c9babf3a8b3492bbccd8888beb6d550fd41e32f4717b8dbb5fc1e66b7907bd79b1cabe3663ce165f5254c6008de4a0e64e3bf7

test:
  secret_key_base: a16e7952e018afa51a0a15f64c02c1a56b39b47ebaf4a55febdda745dedd5f17640668ccb909550df58b16b9611e5a2f3d277cd8a42392b9a28ce639408836d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
